// Additional chapter and a fully playable spreadsheet presentation.
state.extension??={done:[],drafts:{},hints:{}};
const ext=()=>state.extension??=( {done:[],drafts:{},hints:{}} );
const titles=['당직 교대표 복원','마력 예산 대조','배전반 정상화','진술 교차 검증','기록실 전송 암호','비상 통로 설계'];
const rewards=['교대표 복원 완료','배정량: 인사 30 / 시설 22 / 감사 44','배전반 정상화 완료','행위자 A / 유일한 참말 B','기록실 전송 승인','비상 통로 확보'];
let office=false;try{office=localStorage.getItem('office-mode')==='true';}catch{}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const officeButton=document.createElement('button');officeButton.className='quiet';officeButton.id='office-toggle';document.querySelector('.top-actions').prepend(officeButton);
const chapterButton=document.createElement('button');chapterButton.className='quiet';chapterButton.id='chapter-two';chapterButton.onclick=chapterHub;document.querySelector('.top-actions').prepend(chapterButton);
function setOffice(value){office=value;document.body.classList.toggle('office-mode',office);document.title=office?'업무관리대장 — 결재 현황':'마왕성 퇴근 심사';officeButton.textContent=office?'일반 보기 · F2':'업무 모드 · F2';document.querySelector('.brand').textContent=office?'업무관리대장':'♜ 마왕성 퇴근 심사';if(office){sound=false;$('#sound').textContent='소리 켜기';audio?.suspend();}try{localStorage.setItem('office-mode',String(office));}catch{} }
officeButton.onclick=()=>setOffice(!office);document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();setOffice(!office);}});setOffice(office);
const expansionRender=render;render=function(){expansionRender();chapterButton.textContent=office?'추가 검토 '+ext().done.length+'/6':'추가 결재 '+ext().done.length+'/6';if(state.seals.length===3&&ext().done.length<6)$('#objective').textContent='부서 심사를 마쳤습니다. 상단의 추가 결재에서 여섯 검토 항목을 처리하세요.';};
const expansionReset=resetGame;resetGame=function(){expansionReset();ext();render();};
// A prior demo completion keeps the three seals but opens the new chapter.
if(ext().done.length<6)state.ended=false;
const expansionEnding=ending;ending=function(){if(ext().done.length<6){chapterHub();return;}expansionEnding();};
function chapterHub(){const ready=state.seals.length===3;modal(office?'추가 검토 현황':'끝난 줄 알았죠? · 추가 결재',`<p>${ready?'세 부서의 도장은 사전 심사였습니다. 중앙 결재 서버가 여섯 건의 불일치를 발견했습니다. 단서를 대조하여 최종 퇴근 경로를 확보하세요.':'먼저 인사·시설·감사 세 부서 심사를 완료하세요. 아래는 이후 처리할 검토 항목입니다.'}</p><div class="case-list">${titles.map((t,i)=>`<button class="case-row" ${!ready||(i>0&&!ext().done.includes(i-1))?'disabled':''} onclick="openCase(${i})"><span>${String(i+1).padStart(2,'0')}</span><strong>${t}</strong><em>${ext().done.includes(i)?'완료':i===ext().done.length?'검토 가능':'대기'}</em></button>`).join('')}</div><div class="clue">${ext().done.length?ext().done.map(i=>esc(rewards[i])).join('<br>'):'완료한 문서의 결과는 여기에 보관됩니다. 다음 문제의 단서로 쓰일 수 있습니다.'}</div><div class="actions"><button class="secondary" onclick="openNotes()">개인 메모</button>${ext().done.length===6?'<button class="primary" onclick="closeModal();move(\'exit\')">최종 퇴근 신청</button>':''}</div>`);}
function openNotes(){modal('개인 메모',`<p>추론 중인 내용과 숫자를 적어두세요. 입력 즉시 저장됩니다.</p><textarea id="case-notes" rows="8" aria-label="개인 메모" oninput="ext().notes=this.value;save()">${esc(ext().notes||'')}</textarea><div class="actions"><button class="primary" onclick="chapterHub()">검토 목록으로</button></div>`);}
function table(headers,rows){return `<table class="evidence"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function draft(i,k,v){ext().drafts[i]??={};ext().drafts[i][k]=v;save();}
function input(i,k,label){return `<label class="answer-label">${label}<input autocomplete="off" value="${esc(ext().drafts[i]?.[k]||'')}" oninput="draft(${i},'${k}',this.value)" aria-label="${label}"></label>`;}
function select(i,k,label,options){return `<label class="answer-label">${label}<select aria-label="${label}" onchange="draft(${i},'${k}',this.value)"><option value="">선택</option>${options.map(v=>`<option ${ext().drafts[i]?.[k]===v?'selected':''}>${v}</option>`).join('')}</select></label>`;}
function openCase(i){if(state.seals.length!==3||(i>0&&!ext().done.includes(i-1)))return;if(ext().done.includes(i)){modal(titles[i],`<p>이미 처리한 항목입니다.</p><div class="clue">${rewards[i]}</div><button class="primary" onclick="chapterHub()">검토 목록으로</button>`);return;}
let body='';
if(i===0)body=`<p>다섯 직원 A~E가 월~금에 하루씩 근무합니다. 각 직원은 정확히 한 번만 배치됩니다. 훼손된 교대표를 복원하세요.</p>${table(['문서','남아 있는 내용'],[['복무 메일','D는 B 바로 다음 날 출근한다.'],['휴가 신청','C는 E보다 먼저 출근한다.'],['시설 점검','E는 수요일 점검 담당이다.'],['인수인계','A의 근무일은 C의 바로 다음 날이다.']])}<div class="answer-grid">${['월','화','수','목','금'].map((d,n)=>select(i,'d'+n,d+'요일',['A','B','C','D','E'])).join('')}</div>`;
if(i===1)body=`<p>청구량이 아니라 <b>실제 배정량</b>을 복구해야 합니다. 세 기록은 모두 참이고 배정량은 양의 정수입니다.</p>${table(['기록','내용'],[['총무부 원장','세 부서에 실제 배정한 총량은 96이다.'],['인사부 정산','우리 배정량은 시설부보다 8 많다.'],['감사부 통보','우리 배정량은 시설부의 정확히 두 배다.'],['폐기된 초안','인사 40 / 시설 30 / 감사 50 — 청구량이며 배정량 아님']])}<div class="answer-grid">${input(i,'h','인사 배정량')}${input(i,'f','시설 배정량')}${input(i,'a','감사 배정량')}</div>`;
if(i===2){if(!ext().drafts[2]?.board){let b=Array(9).fill(0);[0,4,8].forEach(n=>neighbors(n).forEach(j=>b[j]^=1));draft(2,'board',b);}body=`<p>한 칸을 누르면 그 칸과 상하좌우 인접 칸의 전원이 반전됩니다. 대각선은 바뀌지 않습니다. <b>아홉 칸을 모두 OFF</b>로 만들어 과부하를 해제하세요.</p><div class="switch-grid">${ext().drafts[2].board.map((v,n)=>`<button class="switch ${v?'on':''}" onclick="flipSwitch(${n})" aria-label="${n+1}번 회로 ${v?'ON':'OFF'}">${n+1}<small>${v?'ON':'OFF'}</small></button>`).join('')}</div><button class="secondary" onclick="delete ext().drafts[2];save();openCase(2)">배전반 초기화</button>`;}
if(i===3)body=`<p>A·B·C 중 정확히 한 사람이 원장을 변경했습니다. 아래 세 진술 중 <b>정확히 하나만 참</b>입니다. 행위자와 참말을 한 사람을 각각 고르세요.</p>${table(['직원','진술'],[['A','“B가 원장을 변경했습니다.”'],['B','“나는 변경하지 않았습니다.”'],['C','“A는 변경하지 않았습니다.”']])}<div class="answer-grid">${select(i,'culprit','원장을 변경한 사람',['A','B','C'])}${select(i,'truth','참말을 한 사람',['A','B','C'])}</div>`;
if(i===4)body=`<p>서버는 표를 행 순서대로 읽지 않습니다. 예산 결재에서 얻은 <b>실제 배정량이 작은 부서부터</b> 열을 정렬하고, 각 열을 위에서 아래로 읽어 이어 붙이세요.</p>${table(['인사','시설','감사'],[['7','4','9'],['1','8','3'],['6','2','5']])}<details><summary>완료한 예산 기록 펼치기</summary><p>${rewards[1]}</p></details>${input(i,'code','9자리 전송 암호')}<div class="clue">전송 규약: 첫 열의 세 숫자 → 둘째 열의 세 숫자 → 마지막 열의 세 숫자. 모든 숫자를 한 번씩 사용합니다.</div>`;
if(i===5)body=`<p>기록실에서 출구까지 이동 경로를 설계하세요. 통로는 <b>화살표 방향으로만</b> 통과하며, 마력은 최대 <b>10</b>입니다. 인증 장치가 있는 <b>C를 반드시 지나야</b> 합니다.</p>${table(['통로','소모 마력'],[['시작 → A / 시작 → B','3 / 2'],['A → C / A → D','4 / 2'],['B → C / B → D','2 / 5'],['C → E / D → E','3 / 1'],['E → 출구','3']])}<p class="route-preview">${esc((ext().drafts[5]?.route||['시작']).join(' → '))}</p><div class="actions">${['A','B','C','D','E','출구'].map(n=>`<button class="secondary" onclick="addRoute('${n}')">${n}</button>`).join('')}<button class="secondary" onclick="draft(5,'route',['시작']);openCase(5)">경로 지우기</button></div><div class="clue">짧은 경로라도 C를 빠뜨리면 인증되지 않습니다. 표에 없는 통로는 사용할 수 없습니다.</div>`;
modal('추가 결재 '+(i+1)+' · '+titles[i],body+`<p class="feedback" id="case-feedback" role="status"></p><div class="actions"><button class="primary" onclick="submitCase(${i})">검토 제출</button><button class="secondary" onclick="caseHint(${i})">단계별 힌트</button><button class="secondary" onclick="chapterHub()">목록</button></div>`,'case-modal');}
function neighbors(n){return [n,n%3? n-1:-1,n%3<2?n+1:-1,n>=3?n-3:-1,n<6?n+3:-1].filter(x=>x>=0);}
function flipSwitch(n){const b=ext().drafts[2].board.slice();neighbors(n).forEach(j=>b[j]^=1);draft(2,'board',b);openCase(2);}
function addRoute(n){const r=ext().drafts[5]?.route||['시작'];if(r.length>=7)return;draft(5,'route',[...r,n]);openCase(5);}
function submitCase(i){const d=ext().drafts[i]||{};let ok=false;if(i===0)ok=['C','A','E','B','D'].every((x,n)=>d['d'+n]===x);if(i===1)ok=Number(d.h)===30&&Number(d.f)===22&&Number(d.a)===44;if(i===2)ok=Array.isArray(d.board)&&d.board.every(x=>x===0);if(i===3)ok=d.culprit==='A'&&d.truth==='B';if(i===4)ok=String(d.code||'').replace(/\s/g,'')==='482716935';if(i===5){const costs={'시작A':3,'시작B':2,AC:4,AD:2,BC:2,BD:5,CE:3,DE:1,'E출구':3};const r=d.route||[];let cost=0,valid=r[0]==='시작'&&r.at(-1)==='출구'&&r.includes('C');for(let n=1;n<r.length;n++){const c=costs[r[n-1]+r[n]];if(c===undefined)valid=false;cost+=c||0;}ok=valid&&cost<=10;}
if(!ok){$('#case-feedback').textContent='불일치가 남아 있습니다. 모든 조건을 함께 만족하는지 확인하세요. 입력 내용은 유지됩니다.';return;}
if(!ext().done.includes(i))ext().done.push(i);save();render();modal('검토 완료',`<div class="ending-stamp">승인 ${i+1} / 6</div><p>${rewards[i]}</p><div class="clue">${i===5?'비상 통로를 확보했습니다. 이제 성문에서 최종 퇴근을 신청할 수 있습니다.':'결과가 추가 결재 기록에 보관되었습니다. 다음 항목이 열렸습니다.'}</div><button class="primary" onclick="${i===5?'chapterHub()':`openCase(${i+1})`}">${i===5?'최종 결과 보기':'다음 항목 검토'}</button>`);}
const extraHints=[['두 개의 연속된 쌍을 찾아 수요일의 양쪽에 배치하세요.','C-A와 B-D가 연속 쌍입니다. C가 E보다 앞이므로 C-A는 월·화입니다.','월~금: C, A, E, B, D.'],['시설부 배정량을 x라고 놓고 세 부서 합을 표현하세요.','시설 x, 인사 x+8, 감사 2x. 합은 4x+8=96입니다.','인사 30, 시설 22, 감사 44.'],['같은 칸을 두 번 누르면 원상복구됩니다. 누를 칸의 순서는 결과에 영향을 주지 않습니다.','상단 행을 끄려면 바로 아래 행의 스위치를 이용하는 방식으로 내려가 보세요.','초기화한 뒤 1번, 5번, 9번을 한 번씩 누르세요.'],['행위자를 A, B, C로 각각 가정해 참인 진술 수를 세세요.','B가 행위자라면 A와 C가 모두 참입니다. C가 행위자라면 B와 C가 참입니다.','행위자는 A, 참말을 한 직원은 B입니다.'],['청구량이 아니라 완료한 예산 기록을 사용하세요.','작은 순서는 시설 → 인사 → 감사입니다. 열 안에서는 위에서 아래로 읽습니다.','482 / 716 / 935를 붙이면 482716935입니다.'],['C를 포함하는 경로만 남기고 총비용을 계산하세요.','시작→A→C는 초반에 7을 씁니다. C 이후에는 6이 더 필요합니다.','시작 → B → C → E → 출구. 2+2+3+3=10입니다.']];
function caseHint(i){const n=Math.min(ext().hints[i]||0,2);ext().hints[i]=n+1;save();modal('검토 도움 '+(n+1),`<p>${extraHints[i][n]}</p><div class="actions"><button class="primary" onclick="openCase(${i})">문제로 돌아가기</button>${n<2?`<button class="secondary" onclick="caseHint(${i})">다음 힌트</button>`:''}</div>`);}
const oldHint=$('#hint').onclick;$('#hint').onclick=()=>{if(state.seals.length===3&&ext().done.length<6)caseHint(ext().done.length);else oldHint();};
// Keep the player's earlier progress; the extension state is saved independently.
save();render();
