// Original procedural score and effects. No recordings, downloads or external services.
const gameAudio=(()=>{
 const defaults={enabled:false,music:.28,effects:.55};let cfg={...defaults};
 try{const x=JSON.parse(localStorage.getItem('escape-audio-v1'));if(x)cfg={enabled:false,music:Math.max(0,Math.min(1,Number(x.music)||0)),effects:Math.max(0,Math.min(1,Number(x.effects)||0))};}catch{}
 let ctx,bgm,fx,master,timer,next=0,step=0,noise,lastEffect=0;
 const beat=60/78, eighth=beat/2;
 const chords=[[50,57,60,65],[55,62,65,69],[48,55,59,64],[53,60,64,69],[46,53,57,60],[52,59,62,67],[45,52,55,60],[45,52,58,61]];
 const melodies=[[77,null,76,null,72,null,69,null],[74,null,null,77,null,76,74,null],[76,null,71,null,72,null,null,null],[76,null,null,79,76,null,72,null],[72,null,69,null,65,null,null,null],[74,null,71,null,67,null,69,null],[72,null,null,71,69,null,67,null],[70,null,73,null,76,null,null,null]];
 const hz=n=>440*Math.pow(2,(n-69)/12);
 function persist(){try{localStorage.setItem('escape-audio-v1',JSON.stringify(cfg));}catch{}}
 function ready(){if(ctx)return true;const C=window.AudioContext||window.webkitAudioContext;if(!C)return false;ctx=new C();audio=ctx;master=ctx.createGain();master.gain.value=.65;const comp=ctx.createDynamicsCompressor();comp.threshold.value=-16;comp.ratio.value=5;master.connect(comp);comp.connect(ctx.destination);bgm=ctx.createGain();fx=ctx.createGain();bgm.connect(master);fx.connect(master);noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const a=noise.getChannelData(0);let seed=404;for(let i=0;i<a.length;i++){seed=(seed*1664525+1013904223)>>>0;a[i]=seed/2147483648-1;}volumes();return true;}
 function volumes(){if(!ctx)return;const now=ctx.currentTime;bgm.gain.setTargetAtTime(cfg.music,now,.08);fx.gain.setTargetAtTime(cfg.effects,now,.02);master.gain.setTargetAtTime((cfg.enabled && !office && !document.hidden) ? .65 : 0,now,.04);}
 function note(midi,t,duration,level,channel=bgm,type='sine',slide=null){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(hz(midi),t);if(slide!==null)o.frequency.exponentialRampToValueAtTime(hz(slide),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,level),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(channel);o.start(t);o.stop(t+duration+.025);o.onended=()=>{o.disconnect();g.disconnect();};}
 function hiss(t,duration,level,freq=2400){const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=noise;filter.type='bandpass';filter.frequency.value=freq;filter.Q.value=.7;g.gain.setValueAtTime(level,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(filter);filter.connect(g);g.connect(fx);src.start(t);src.stop(t+duration);src.onended=()=>{src.disconnect();filter.disconnect();g.disconnect();};}
 function playStep(n,t){const bar=Math.floor(n/8)%16,chord=chords[bar%8],pos=n%8;if(pos===0||pos===5)chord.slice(1).forEach((p,j)=>{note(p,t+j*.012,1.1,.075);note(p+12,t+j*.012,.35,.016);});if(pos===0||pos===4)note(chord[0]-12,t,.55,.19,bgm,'triangle');const melody=melodies[bar%8][pos];if(melody!==null&&(bar<8||pos%2===0))note(melody,t,.58,.09,bgm);}
 function tick(){if(!ctx||ctx.state!=='running'||!cfg.enabled||office||document.hidden||!state.started||state.ended)return;if(next<ctx.currentTime)next=ctx.currentTime+.06;while(next<ctx.currentTime+.25){playStep(step,next);next+=eighth*(step%2===0?1.10:.90);step++;}}
 function schedule(){if(timer)clearInterval(timer);if(ctx){next=ctx.currentTime+.08;timer=setInterval(tick,100);tick();}}
 async function enable(v){if(office&&v){toast('업무 모드에서는 무음입니다. 일반 보기로 바꾼 뒤 소리를 켜세요.');return;}cfg.enabled=Boolean(v);sound=cfg.enabled;persist();if(!v){volumes();if(timer)clearInterval(timer);timer=null;return;}try{if(!ready())throw new Error('unsupported');await ctx.resume();volumes();schedule();}catch{cfg.enabled=false;sound=false;toast('이 브라우저에서 소리를 시작하지 못했습니다. 무음으로 계속할 수 있습니다.');}}
 function effect(kind){if(!ctx||ctx.state!=='running'||!cfg.enabled||office||document.hidden)return;const t=ctx.currentTime;if(t-lastEffect<.07&&!['mimic','glass','ending'].includes(kind))return;lastEffect=t;switch(kind){case'click':note(69,t,.05,.13,fx,'triangle');break;case'collect':[76,83].forEach((n,i)=>note(n,t+i*.07,.24,.18,fx));break;case'success':[62,69,74].forEach((n,i)=>note(n,t+i*.10,.45,.18,fx));break;case'fail':note(46,t,.19,.12,fx,'triangle',42);break;case'stone':hiss(t,.24,.20,220);note(28,t,.23,.10,fx,'triangle');break;case'cloth':hiss(t,.10,.11,1700);break;case'mimic':[42,47,38].forEach((n,i)=>note(n,t+i*.10,.11,.22,fx,'triangle',n-6));break;case'glass':[81,88,93].forEach((n,i)=>note(n,t+i*.11,.7,.10,fx));break;case'parcel':hiss(t,.5,.2,1100);note(60,t+.48,.08,.19,fx,'triangle');break;case'ending':[62,65,69,74,77,81].forEach((n,i)=>note(n,t+i*.15,1.1,.20,fx));break;}}
 document.addEventListener('visibilitychange',()=>{if(!ctx)return;if(document.hidden){master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setValueAtTime(0,ctx.currentTime);ctx.suspend().catch(()=>{});}else if(cfg.enabled&&!office){ctx.resume().then(()=>{volumes();next=ctx.currentTime+.1;}).catch(()=>{});}});
 return{cfg,enable,effect,update(kind,value){cfg[kind]=Number(value);volumes();persist();},start(){if(cfg.enabled){ctx?.resume().catch(()=>{});schedule();}},stop(){if(timer)clearInterval(timer);timer=null;},mute(){cfg.enabled=false;sound=false;volumes();if(ctx)ctx.suspend().catch(()=>{});if(timer)clearInterval(timer);timer=null;persist();}};
})();
// Silence the old generic beep to prevent overlapping duplicate feedback.
tone=function(){};
function audioSettings(){panel('소리 설정',`<p>직접 만든 전자 피아노·베이스 BGM과 합성 효과음입니다. 소리를 끄고도 모든 퍼즐을 풀 수 있습니다.</p><div class="actions"><button class="primary" onclick="gameAudio.enable(${!gameAudio.cfg.enabled}).then(audioSettings)">${gameAudio.cfg.enabled?'전체 음소거':'소리 켜기'}</button><button class="secondary" onclick="gameAudio.effect('collect')">효과음 미리 듣기</button></div><div class="audio-sliders"><label>BGM <output id="music-percent">${Math.round(gameAudio.cfg.music*100)}%</output><input type="range" min="0" max="1" step=".01" value="${gameAudio.cfg.music}" aria-label="BGM 볼륨" oninput="gameAudio.update('music',this.value);document.getElementById('music-percent').textContent=Math.round(this.value*100)+'%'"></label><label>효과음 <output id="effects-percent">${Math.round(gameAudio.cfg.effects*100)}%</output><input type="range" min="0" max="1" step=".01" value="${gameAudio.cfg.effects}" aria-label="효과음 볼륨" oninput="gameAudio.update('effects',this.value);document.getElementById('effects-percent').textContent=Math.round(this.value*100)+'%'"></label></div><p class="sub">업무 모드에서는 무음 · 다른 탭에서는 일시정지 · 새로고침 후에는 직접 소리를 켜주세요.</p>`);}
$('#sound').textContent='소리 설정';$('#sound').onclick=audioSettings;
const officeBeforeAudio=setOffice;setOffice=function(v){officeBeforeAudio(v);if(v)gameAudio.mute();$('#sound').textContent='소리 설정';};
const startBeforeAudio=startGame;startGame=function(){startBeforeAudio();gameAudio.start();};
const introBeforeAudio=intro;intro=function(){introBeforeAudio();const button=$('#modal').querySelector('button.primary');if(button){button.textContent='무음으로 시작';const audible=document.createElement('button');audible.className='secondary';audible.textContent=office?'업무 모드 · 무음':'소리 켜고 시작';audible.disabled=office;audible.onclick=async()=>{await gameAudio.enable(true);startGame();};button.after(audible);}};
const grantBeforeAudio=grant;grant=function(id){const existed=owns(id);grantBeforeAudio(id);if(!existed)gameAudio.effect('collect');};
const turnBeforeAudio=turnPipe;turnPipe=function(i){turnBeforeAudio(i);gameAudio.effect('stone');};
const relayBeforeAudio=flipRelay;flipRelay=function(i){relayBeforeAudio(i);gameAudio.effect('click');};
const wipeBeforeAudio=wipeCell;wipeCell=function(i){const previous=P().wiped.length;wipeBeforeAudio(i);if(P().wiped.length>previous)gameAudio.effect('cloth');};
const useBeforeAudio=useItem;useItem=function(id,target){const had=has('facility');useBeforeAudio(id,target);if(!had&&has('facility'))gameAudio.effect('mimic');};
const mirrorBeforeAudio=checkMirror;checkMirror=function(){const before=S().shadow;mirrorBeforeAudio();gameAudio.effect(!before&&S().shadow?'glass':'click');};
const wireBeforeAudio=checkWires;checkWires=function(){wireBeforeAudio();gameAudio.effect(relayStages()[4].every((v,i)=>v===desiredSignals[i])?'success':'fail');};
const parcelBeforeAudio=sendParcel;sendParcel=function(){gameAudio.effect('parcel');parcelBeforeAudio();};
const endingBeforeAudio=ending;ending=function(){gameAudio.stop();endingBeforeAudio();gameAudio.effect('ending');};
const resetBeforeAudio=resetGame;resetGame=function(){gameAudio.mute();resetBeforeAudio();};
