// Object-based edition. Earlier editions keep their own saves.
const STORY_KEY='demon-office-objects-v4';
const newStory=()=>({...fresh(),story:{pipes:[1,1,2,2,1,0,3,1,1],crank:false,drawer:false,thawed:false,books:[2,0,3,1],archive:false,clean:false,overlay:false,rotation:0,mirror:[],shadow:false,gear:false,blind:false,lamp:null,screen:0,notes:'',clues:[],pin:null,hints:{}}});
try{const s=JSON.parse(localStorage.getItem(STORY_KEY));state=s?.story&&Array.isArray(s.items)?s:newStory();}catch{state=newStory();}
const S=()=>state.story;
const owns=id=>state.items.includes(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
save=function(){try{localStorage.setItem(STORY_KEY,JSON.stringify(state));}catch{$('#save-status').textContent='현재 창에서 진행 중 · 저장 불가';}};
let office=false,activeObject=null,bookPick=null;
try{office=localStorage.getItem('office-mode')==='true';}catch{}
const modeButton=document.createElement('button');modeButton.className='quiet';document.querySelector('.top-actions').prepend(modeButton);
function setOffice(v){office=v;document.body.classList.toggle('office-mode',v);document.title=v?'업무관리대장 — 문서 검토':'마왕성 퇴근 심사 · 그림자 분실 사건';modeButton.textContent=v?'일반 보기 · F2':'업무 모드 · F2';document.querySelector('.brand').textContent=v?'업무관리대장':'♜ 마왕성 퇴근 심사';if(v){sound=false;audio?.suspend();$('#sound').textContent='소리 켜기';}try{localStorage.setItem('office-mode',String(v));}catch{}}
modeButton.onclick=()=>setOffice(!office);document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();setOffice(!office);}});setOffice(office);
Object.assign(itemNames,{packet:['▤','퇴실 원본 봉투'],badge:['▣','임시 사원증'],cloth:['▱','광택 천'],lantern:['◈','휴대등'],crank:['↳','황동 손잡이'],film:['▧','구멍 난 투명판'],gear:['⚙','차광막 톱니'],plate:['▰','그을린 명판'],polished:['▦','닦은 명판']});
const glyphs={moon:'☾',key:'⚿',feather:'❧',sun:'☀',wave:'≋',eye:'◉',crown:'♛',flame:'♨',leaf:'♧'};
const names={moon:'달',key:'열쇠',feather:'깃털',sun:'태양',wave:'물결',eye:'눈',crown:'왕관',flame:'불꽃',leaf:'잎'};
const face=['moon','eye','key','feather','sun','crown','wave','flame','leaf'];
const docs={
 rules:['퇴실 사고 접수','18:04 — 직원은 출구를 통과했으나 그림자가 반대쪽에 남음.\n시설부의 등록 명판 소실 확인.\n복구 절차: 명판 회수 → 반사경으로 본인 대조 → 그림자 동반 퇴실.\n비품이 증거물을 삼키는 사고는 이번 달 세 번째다.'],
 route:['접힌 복도의 정비도','시설부 연결관은 왼쪽 위에서 들어와 오른쪽 아래로 나간다.\n회전축은 황동 사각형. 손잡이 분실 시 창문 비품을 확인할 것.\n누수로 지워진 연필선: ① ─ ②\n　　　　　　　　　│\n　　　　　　　 ④ ─ ⑤\n　　　　　　　 │\n　　　　　　　 ⑦ ─ ⑧ ─ ⑨'],
 cooling:['냉각 보관 기록','만년빙은 닿은 물체에서 열만 빼앗는다. 빛과 형태는 보존된다.\n지난번엔 촛불을 넣었다. 불이 안 꺼져서 냉장고인지 전등인지 모르게 됐다.\n손잡이에 성에가 끼면 작은 열원으로 녹일 것.'],
 feeding:['미믹의 반려 식단','등불: 유리 씹힘.\n얼음: 차갑지만 어두움.\n횃불: 혀 데임.\n“밝은 건 좋은데, 뜨거운 건 싫다니까요.”'],
 shelf:['반납대의 쪽지','책등 양끝의 문장은 원래 한 줄로 이어져 있었다.\n왼쪽 고정 장식은 달, 오른쪽은 열쇠. 이웃한 문양이 같을 때만 철침이 물린다.\n자료실장: 책 제목은 안 읽어도 됩니다. 어차피 전부 회의록이에요.'],
 registration:['명판 판독 지침','격자의 문양은 위쪽 행부터, 각 행에서는 왼쪽부터 읽는다.\n구멍 난 대조판과 명판의 잘린 모서리를 맞출 것.\n그림자는 유리 너머에서 읽는다. 반사면의 좌우를 잊지 말 것.'],
 light:['경비원의 관측 일지','창빛과 휴대등이 함께 켜지면 그림자가 둘로 갈라진다.\n출구의 센서는 오른쪽에 있다. 그림자는 광원의 반대편으로 뻗는다.\n멀리 있는 등: 작은 그림자. 가까이 있는 등: 큰 그림자.\n높이가 센서 틀에 맞지 않으면 문이 열리지 않았다.'],
 plate:['명판 문양의 사본','오른쪽 위 모서리가 잘려 있다.\n달　　눈　　열쇠\n깃털　태양　왕관\n물결　불꽃　잎'],
 film:['대조판의 사본','기준 상태: 왼쪽 위 모서리가 잘림.\n구멍은 왼쪽 위 · 위 가운데 · 정중앙.\n모서리를 맞춘 뒤 구멍으로 보이는 문양만 판독한다.']
};
function discover(id){if(!S().clues.includes(id)){S().clues.push(id);save();}}
function readDoc(id){discover(id);panel(docs[id][0],`<div class="document-body">${esc(docs[id][1])}</div><button class="secondary" onclick="pinDoc('${id}')">이 자료를 옆에 고정</button>`);}
function pinDoc(id){S().pin=S().pin===id?null:id;save();notebook();}
function pinned(){const d=docs[S().pin];return d?`<aside class="pinned-clue"><strong>고정한 자료 · ${esc(d[0])}</strong><div>${esc(d[1])}</div><button class="secondary" onclick="S().pin=null;save();this.closest('.pinned-clue').remove()">고정 해제</button></aside>`:'';}
function panel(title,body,target=null){activeObject=target;modal(title,`<div class="object-layout"><div>${body}${target?useBar(target):''}</div>${pinned()}</div>`,'object-modal');}
function useBar(target){return `<div class="tool-tray"><label for="use-item">이곳에 사용할 소지품</label><div><select id="use-item"><option value="">물건 선택</option>${state.items.map(id=>`<option value="${id}" ${selected===id?'selected':''}>${itemNames[id][1]}</option>`).join('')}</select><button class="secondary" onclick="useItem(document.getElementById('use-item').value,'${target}')">사용</button></div><p class="use-feedback" role="status" id="use-feedback"></p></div>`;}
function reject(message){const el=$('#use-feedback');if(el)el.textContent=message;else toast(message);}
function grant(id){if(!owns(id))state.items.push(id);save();render();}
function remove(id){state.items=state.items.filter(x=>x!==id);if(selected===id)selected=null;}
function eventPanel(title,text){save();render();panel(title,`<p>${text}</p><button class="primary" onclick="closeModal()">계속 탐색</button>`);}
function take(id){grant(id);toast(itemNames[id][1]+' 획득');closeModal();}
function notebook(){panel('조사 수첩',`<p>읽은 자료만 기록됩니다. 자료 하나를 고정하면 다른 장치를 조사하면서 비교할 수 있습니다.</p><div class="clue-list">${S().clues.map(id=>`<button class="secondary" onclick="readDoc('${id}')">${docs[id][0]}${S().pin===id?' · 고정됨':''}</button>`).join('')||'아직 발견한 자료가 없습니다.'}</div><label for="personal-notes">내 메모</label><textarea id="personal-notes" rows="4" oninput="S().notes=this.value;save()">${esc(S().notes)}</textarea>`);}
$('#approval').textContent='조사 수첩';$('#approval').onclick=notebook;

// The archive is a playable schematic room, with no background image.
rooms.archive={en:'기록 보관실',title:'기록실 · 반납되지 않은 이름',note:'누군가 책을 순서 없이 밀어 넣었다. 책등 사이의 철침이 서로 걸려 서랍을 붙잡고 있다.',art:()=>`<div class="archive-scene"><div class="archive-heading"><span>마왕성 중앙기록실</span><strong>반납은 제자리에.</strong><p>회수된 이름과 잃어버린 그림자의 기록을 보관합니다.</p></div><div class="archive-shelves">${S().books.map(i=>`<div class="book-spine">${glyphs[bookEnds[i][0]]}<span>야간 회의록</span>${glyphs[bookEnds[i][1]]}</div>`).join('')}</div><div class="archive-desk"><span>명판 판독 작업대</span><span>${S().archive?'하부 서랍 열림':'철침 잠금'}</span></div></div>`,spots:[['철침 서가',5,34,52,32,'shelf'],['반납대 쪽지',64,33,29,20,'shelfNote'],['판독 작업대',8,78,46,18,'workbench'],['판독 지침',64,67,29,28,'registration']]};
const bookEnds=[['moon','feather'],['feather','wave'],['wave','sun'],['sun','key']];
rooms.hr.spots.push(['책상 서랍',31,66,25,17,'drawer']);
rooms.audit.spots=[['반사면 관리 기록',10,34,18,32,'registration'],['이름 반사경',31,10,30,67,'mirror'],['창문 걸쇠',77,7,18,28,'window']];
rooms.exit.spots=[['차광막 기어함',3,8,21,28,'blind'],['성문과 광학 센서',32,15,35,68,'terminal'],['경비 관측 일지',75,49,21,28,'light']];
rooms.hr.note='문을 나서려던 순간 그림자만 남았다. 책상 위 사고 접수철에 내 사원증이 끼워져 있다.';
rooms.audit.title='감사부 · 주인 없는 반사면';rooms.audit.note='거울 아래에는 명판 홈이 있다. 창문의 손잡이는 복도 회전축과 비슷한 사각형이다.';
rooms.facility.note='미믹의 이빨 사이에서 내 명판이 반짝인다. 식판에는 거절한 음식들이 그대로 쌓여 있다.';
rooms.exit.title='성문 · 둘이서 나가는 문';rooms.exit.note='문 옆에는 작은 사람이 그려진 센서가 있다. 경비원이 남긴 관측 일지가 바람에 흔들린다.';
const oldRender=render;
render=function(){oldRender();const order=['hr','archive','audit','facility','exit'];$('#nav').innerHTML=order.map(id=>`<button class="nav ${state.room===id?'active':''}" ${id==='facility'&&!has('hr')?'disabled':''} onclick="move('${id}')">${{hr:'인사부',archive:'기록실',audit:'감사부',facility:'시설부',exit:'성문'}[id]}${id==='facility'&&!has('hr')?' · 복도 단절':''}</button>`).join('');$('#stage').classList.toggle('schematic',state.room==='archive');$('#item-note').textContent=selected?`${itemNames[selected][1]} 선택 중 · 사물을 조사하고 ‘사용’하세요.`:'소지품을 누르면 조사·뒤집기·조합이 가능합니다.';$('#objective').textContent=state.ended?'본인과 그림자, 모두 퇴실했습니다.':S().shadow?'돌아온 그림자를 성문의 센서에 맞춰야 한다.':has('facility')?'명판은 회수했다. 기록실과 반사경에서 이름을 복구할 방법을 찾자.':has('hr')?'미믹에게서 명판을 회수하자. 기록실의 판독 도구도 필요할 것 같다.':'시설부 복도가 끊어졌다. 인사부·기록실·감사부를 먼저 살펴보자.';$('#seals').innerHTML=[['hr','통로 복구'],['facility','명판 회수'],['audit','그림자 복원']].map(([id,label])=>`<div class="seal ${has(id)?'done':''}">${label}${has(id)?' ✓':''}</div>`).join('');$('#seal-count').textContent=`사건 진행 ${state.seals.length} / 3${S().archive?' · 판독 도구 확보':''}`;$('#narration').textContent=state.room==='hr'&&has('hr')?'벽이 물러나 시설부 통로가 생겼다. 열린 통로에서 미믹이 재채기하는 소리가 들린다.':rooms[state.room].note;const status=document.createElement('div');status.className='world-status';status.textContent=state.room==='facility'?(has('facility')?'명판 회수 완료':S().thawed?'보관함 해동됨':'보관함 동결'):state.room==='archive'?(S().archive?'잠금 해제 · 작업대 사용 가능':'서가 철침 잠김'):state.room==='audit'?(S().shadow?'그림자 복원됨':'반사경 대기'):state.room==='exit'?(S().blind?'차광막 닫힘':'창빛 유입'):has('hr')?'시설부 통로 연결':'시설부 통로 단절';$('#stage').append(status);};
move=function(id){if(!rooms[id]||(id==='facility'&&!has('hr')))return;state.room=id;selected=null;save();render();};
resetGame=function(){state=newStory();selected=null;bookPick=null;save();render();intro();};
intro=function(){panel('퇴근하려다, 그림자를 잃었다.',`<p>18시 04분. 몸은 성문을 나섰지만 그림자는 따라오지 않았다.</p><p>뼈 대리가 사고 접수철을 내민다.<br>“이름이 지워진 그림자는 못 나갑니다. 시설부에서 명판부터 찾아오세요. 그쪽 복도도 좀… 접혔지만요.”</p><div class="clue">사물을 조사하고, 도구를 사용해 공간을 바꾸세요.<br>자료는 수첩에 남고, 하나를 고정해 비교할 수 있습니다.<br>시간 제한 없음 · F2 업무 모드 · 소리 없이 모든 퍼즐 해결 가능</div><button class="primary" onclick="startGame()">접수철을 받아 든다</button><p class="sub">새 사건판은 이전 진행과 별도로 저장됩니다.</p>`);};
const itemDetails={badge:['사진 대신 빈 실루엣. 인사부 발급 임시 사원증이다.','뒷면 아래에 얇은 접점이 있다. 각인: “본인 서랍 접근용”.'],cloth:['금속 광택용 천. 모서리에 검댕이 묻어 있다.','세탁 금지. 물에 담그면 저주가 빠집니다.'],lantern:['휴대용 작업등. 넓은 받침이 달려 있다.','광원 시험: 같은 물체도 빛과의 거리에 따라 그림자 크기가 달라진다.'],crank:['끝이 사각형인 황동 손잡이.','창문과 정비축에 공용으로 쓰는 규격이다.'],candle:['추위에도 꺼지지 않는 불씨. 손을 가까이 대면 뜨겁다.','불씨 영구 보증. 촛농은 보증하지 않습니다.'],ice:['푸른 얼음. 가까이 대면 손의 열기가 빠져나간다.','표면 아래 작은 빛이 그대로 비친다.'],cold:['얼음 안에 불씨가 타오른다. 빛은 밝고 손은 차갑다.','유리도 촛농도 없다. 한입 크기다.'],gear:['차광막 수리용 톱니. 중앙에 홈이 있다.','기록실 대출 비품. 경비실 반납 예정.'],plate:['검은 검댕 아래에 아홉 칸이 희미하게 보인다.','목걸이 고리에 내 사원번호가 적혀 있다.'],polished:['아홉 문양이 새겨진 명판. 오른쪽 위 모서리가 잘려 있다.','반사면 대조용. 문양의 이름이 본인의 이름을 대신한다.'],film:['아홉 칸 가운데 세 곳이 뚫린 투명판. 왼쪽 위 모서리가 잘려 있다.','같은 규격의 명판 위에 겹쳐 판독한다.']};
selectItem=function(id){if(!owns(id))return;selected=id;render();inspectItem(id);};
function inspectItem(id,back=false){if(!owns(id))return;const d=itemDetails[id];if(id==='polished')discover('plate');if(id==='film')discover('film');panel(itemNames[id][1],`<div class="item-exhibit">${itemNames[id][0]}<small>${back?'뒷면':'앞면'}</small></div><p>${d[back?1:0]}</p>${id==='polished'&&!back?plateGrid(false):''}${id==='film'&&!back?'<div class="document-body">◯　◯　■<br>■　◯　■<br>■　■　■</div>':''}<div class="actions"><button class="secondary" onclick="inspectItem('${id}',${!back})">뒤집기</button><button class="secondary" onclick="selected='${id}';render();closeModal()">손에 들고 돌아가기</button></div><div class="tool-tray"><label for="combine-item">다른 소지품과 조합</label><select id="combine-item">${state.items.filter(x=>x!==id).map(x=>`<option value="${x}">${itemNames[x][1]}</option>`).join('')}</select><button class="secondary" onclick="combine('${id}',document.getElementById('combine-item').value)">조합</button><p id="use-feedback" role="status"></p></div>`);}
function combine(a,b){if(!owns(a)||!owns(b)||a===b)return;const pair=[a,b];if(pair.includes('candle')&&pair.includes('ice')){remove('candle');remove('ice');grant('cold');eventPanel('불씨는 남고, 열기만 사라졌다','양초의 불씨가 얼음 안으로 스며든다. 손바닥에 올려놓아도 뜨겁지 않다.');return;}if(pair.includes('cloth')&&pair.includes('plate')){remove('plate');S().clean=true;grant('polished');discover('plate');eventPanel('검댕 아래에 아홉 문양','명판을 닦자 문양이 드러났다. 다 읽기에는 너무 많다. 오른쪽 위 모서리가 비스듬히 잘려 있다.');return;}if(pair.includes('film')&&pair.includes('polished')){S().overlay=true;save();workbench();return;}reject('맞물리는 부분도, 눈에 띄는 변화도 없다. 두 물건의 성질을 다시 살펴보자.');}
function useItem(id,target){if(!id||!owns(id)){reject('사용할 소지품을 골라주세요.');return;}
 if(target==='drawer'&&id==='badge'){if(S().drawer){reject('이미 열린 서랍이다.');return;}S().drawer=true;grant('cloth');grant('lantern');eventPanel('접점이 맞물리며 서랍이 열렸다','광택 천과 휴대등을 챙겼다. 바닥에는 “퇴근 전에 빌린 물건 반납”이라고 적혀 있다. 오늘은 예외로 하자.');return;}
 if(target==='org'&&id==='crank'){S().crank=true;remove(id);save();pipePanel();return;}
 if(target==='ice'&&id==='candle'){S().thawed=true;save();render();interact('ice');return;}
 if(target==='mimic'&&id==='cold'){remove(id);seal('facility');grant('plate');eventPanel('시설부가 증거물을 반납했다','미믹이 푸른 불씨를 삼켰다. 이빨 사이에서 그을린 명판이 튀어나왔다.\n“소화가 안 돼서 갖고 있었어요. 증거 인멸은 아닙니다.”');return;}
 if(target==='mimic'){reject(id==='ice'?'미믹이 코를 찡그린다. “차갑긴 한데, 어두워요.”':id==='candle'?'미믹이 혀를 숨긴다. “그거 때문에 데었다니까!”':'미믹이 입을 닫는다. “식판 옆 반려 목록 좀 읽어주세요.”');return;}
 if(target==='workbench'&&(id==='film'||id==='polished')){if(!owns('film')||!owns('polished')){reject('작업대의 안내에는 명판과 대조판, 두 장을 겹치라고 적혀 있다.');return;}S().overlay=true;save();workbench();return;}
 if(target==='mirror'&&id==='polished'){if(!S().overlay){reject('아홉 문양이 모두 비친다. 세 문양만 남겨 읽을 대조판이 필요하다.');return;}S().mirrorMounted=true;save();mirrorPanel();return;}
 if(target==='blind'&&id==='gear'){S().gear=true;remove(id);save();render();interact('blind');return;}
 if(target==='terminal'&&id==='lantern'){S().lamp='far';save();exitPanel();return;}
 reject(target==='drawer'?'열쇠 구멍이 아니라 얇은 접점 슬롯이다.':target==='org'?'회전축은 사각형이다. 손으로는 돌아가지 않는다.':target==='ice'?'내용물보다 손잡이의 성에가 먼저 문제다.':target==='mirror'?'홈에는 얇은 금속 명판만 들어갈 것 같다.':'이 물건으로는 장치가 움직이지 않는다.');
}

// A traversable light circuit changes the room connection, rather than awarding a code.
const pipeBase=[['W','E'],['W','S'],['N','E'],['E','S'],['N','W'],['N','S'],['N','E'],['W','E'],['W','E']];
const dirs=['N','E','S','W'],opposite={N:'S',E:'W',S:'N',W:'E'};
function ports(i){return pipeBase[i].map(d=>dirs[(dirs.indexOf(d)+S().pipes[i])%4]);}
function pipePanel(){if(has('hr')){panel('열린 시설부 통로','<p>조직도 뒤편의 연결관에 빛이 흐른다. 벽 너머로 시설부의 문이 보인다.</p>');return;}panel('조직도 뒤편 · 접힌 복도',`<p>${S().crank?'손잡이가 회전축에 맞물려 있다. 조각을 돌리면 벽 너머의 복도도 움직인다.':'회전축의 손잡이가 빠져 있다. 축 끝은 사각형이다.'}</p><div class="pipe-board"><div class="pipe-port inlet">입구 →</div><div class="pipe-grid">${pipeBase.map((_,i)=>`<button class="pipe-tile" ${S().crank?'':'disabled'} onclick="turnPipe(${i})" aria-label="${i+1}번 복도 회전, 연결 ${ports(i).join(',')}"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="8" fill="currentColor"/>${ports(i).map(d=>`<path d="M50 50L${{N:'50 0',E:'100 50',S:'50 100',W:'0 50'}[d]}" stroke="currentColor" stroke-width="12"/>`).join('')}</svg><small>${i+1}</small></button>`).join('')}</div><div class="pipe-port outlet">→ 시설부</div></div><p class="sub">조각을 누르면 90도 회전합니다. 모든 칸을 지날 필요는 없습니다.</p><p id="pipe-result" role="status"></p><div class="actions"><button class="secondary" onclick="readDoc('route')">옆의 정비도 읽기</button><button class="primary" ${S().crank?'':'disabled'} onclick="tracePipe()">통로에 빛 흘리기</button></div>`,'org');}
function turnPipe(i){S().pipes[i]=(S().pipes[i]+1)%4;save();pipePanel();$('#modal').querySelectorAll('.pipe-tile')[i].focus();}
function tracePipe(){let todo=ports(0).includes('W')?[0]:[],seen=new Set();while(todo.length){const i=todo.shift();if(seen.has(i))continue;seen.add(i);for(const d of ports(i)){let j=d==='N'?i-3:d==='S'?i+3:d==='E'?i+1:i-1;if(j<0||j>8||(d==='E'&&i%3===2)||(d==='W'&&i%3===0))continue;if(ports(j).includes(opposite[d]))todo.push(j);}}document.querySelectorAll('.pipe-tile').forEach((el,i)=>el.classList.toggle('lit',seen.has(i)));if(!seen.has(8)||!ports(8).includes('E')){$('#pipe-result').textContent=seen.size?`빛이 ${seen.size}칸을 지난 곳에서 멎었다. 밝아진 끝을 확인하자.`:'왼쪽 위 입구부터 막혀 있다.';return;}seal('hr');eventPanel('복도가 펴지며 새 문이 나타났다','빛이 끝까지 흐르자 벽이 바깥으로 밀려났다. 이제 시설부에 갈 수 있다.\n뼈 대리: “조직 개편이 끝났네요. 이번에는 건물이 먼저 퇴근할 뻔했어요.”');}

function shelfPanel(){if(S().archive){panel('철침이 풀린 서가','<p>책등의 문양이 한 줄로 이어졌다. 아래 서랍에서 투명 대조판과 차광막 톱니를 챙겼다.</p>');return;}panel('반납 서가',`<p>네 권의 책을 관통한 철침이 아래 서랍까지 이어진다. 두 책을 차례로 선택하면 자리를 바꿀 수 있다.</p><div class="shelf-end">고정 장식 ${glyphs.moon} <span>${glyphs.key} 고정 장식</span></div><div class="book-puzzle">${S().books.map((id,i)=>`<button class="puzzle-book ${bookPick===i?'chosen':''}" aria-label="${i+1}번째 책 ${names[bookEnds[id][0]]}, ${names[bookEnds[id][1]]}" onclick="swapBook(${i})"><b>${glyphs[bookEnds[id][0]]}</b><span>${['보안 회의','시설 회의','급식 회의','퇴근 회의'][id]}</span><b>${glyphs[bookEnds[id][1]]}</b></button>`).join('')}</div><p id="shelf-feedback" role="status"></p><div class="actions"><button class="secondary" onclick="readDoc('shelf')">반납대 쪽지 읽기</button><button class="primary" onclick="checkShelf()">책을 안쪽으로 밀기</button></div>`);}
function swapBook(i){if(bookPick===null){bookPick=i;}else{[S().books[i],S().books[bookPick]]=[S().books[bookPick],S().books[i]];bookPick=null;save();}shelfPanel();}
function checkShelf(){const b=S().books.map(i=>bookEnds[i]);const joins=[b[0][0]==='moon',...b.slice(1).map((x,i)=>b[i][1]===x[0]),b[3][1]==='key'];if(!joins.every(Boolean)){$('#shelf-feedback').textContent=`철침 ${joins.filter(Boolean).length} / 5곳이 맞물린다. 나머지 이음새에서 책이 걸린다.`;return;}S().archive=true;grant('film');grant('gear');eventPanel('책 뒤에서 서랍이 밀려 나왔다','구멍 난 투명판과 작은 톱니가 들어 있다. 톱니에는 “성문 차광막 반납용”이라는 꼬리표가 달려 있다.\n서랍 바닥의 판독 지침도 살펴보자.');}
function holes(){let h=[0,1,4];for(let n=0;n<S().rotation;n++)h=h.map(i=>(i%3)*3+2-Math.floor(i/3));return h;}
function plateGrid(mask,reflected=false){const h=holes();return `<div class="plate-grid ${mask?'masked':''}"><span class="plate-notch">명판 모서리 ◩</span>${Array.from({length:9},(_,i)=>{const src=reflected?Math.floor(i/3)*3+2-i%3:i;return `<div class="glyph-cell ${mask&&!h.includes(src)?'covered':''}"><span>${mask&&!h.includes(src)?'·':glyphs[face[src]]}</span><small>${mask&&!h.includes(src)?'가림':names[face[src]]}</small></div>`;}).join('')}</div>`;}
function workbench(){if(!owns('polished')){panel('명판 판독 작업대',`<p>작업등 아래에 아홉 칸짜리 받침이 있다. 금속판을 올려 판독하는 자리 같다.</p><button class="secondary" onclick="readDoc('registration')">판독 지침 읽기</button>`,'workbench');return;}discover('plate');panel('판독 작업대',`<p>${S().overlay?'명판 위에 투명판을 겹쳤다. 두 판의 잘린 모서리를 살펴보자.':'닦은 명판을 받침에 올렸다. 문양은 아홉 개, 반사경의 입력 홈은 세 개다.'}</p>${plateGrid(S().overlay)}${S().overlay?`<div class="alignment"><span>명판 모서리: 오른쪽 위</span><span>투명판 모서리: ${['왼쪽 위','오른쪽 위','오른쪽 아래','왼쪽 아래'][S().rotation]}</span></div><button class="secondary" onclick="S().rotation=(S().rotation+1)%4;save();workbench()">투명판 90° 돌리기</button>`:''}<div class="actions"><button class="secondary" onclick="readDoc('registration')">판독 지침 읽기</button><button class="secondary" onclick="readDoc('plate')">명판 사본 보기</button></div>`,'workbench');}
function mirrorPanel(){if(S().shadow){panel('이제 나를 따라오는 그림자','<p>거울 속 사람이 나와 동시에 손을 든다. 발밑으로 그림자가 돌아왔다. 이제 성문의 센서를 작동시킬 수 있다.</p>');return;}panel('이름 반사경',`<p>${S().mirrorMounted?'겹친 명판을 홈에 끼웠다. 유리 너머의 문양은 좌우가 뒤집혀 있다.':'거울 아래의 홈은 비어 있다. 옆에 세 개의 작은 입력창이 있다.'}</p>${S().mirrorMounted?plateGrid(true,true):'<div class="empty-mirror">이름 없는 그림자<br><small>명판 대조 대기</small></div>'}<div class="rune-input">${[0,1,2].map(i=>`<span>${glyphs[S().mirror[i]]||'—'}</span>`).join('')}</div><div class="rune-keys">${['moon','key','feather','sun','wave','eye','crown','flame','leaf'].map(id=>`<button class="secondary" onclick="callRune('${id}')">${glyphs[id]} ${names[id]}</button>`).join('')}</div><div class="actions"><button class="secondary" onclick="S().mirror=[];save();mirrorPanel()">입력 지우기</button><button class="primary" onclick="checkMirror()">이름 부르기</button><button class="secondary" onclick="readDoc('registration')">관리 기록 읽기</button></div><p id="mirror-feedback" role="status"></p>`,'mirror');}
function callRune(id){if(S().mirror.length===3)S().mirror=[];S().mirror.push(id);save();mirrorPanel();}
function checkMirror(){if(!S().mirrorMounted){$('#mirror-feedback').textContent='대조할 명판이 없어 유리가 반응하지 않는다.';return;}if(S().rotation!==1){$('#mirror-feedback').textContent='명판과 대조판의 가장자리가 어긋나 유리가 흐려진다. 작업대에서 모서리를 확인하자.';return;}if(S().mirror.join()!=='key,crown,sun'){$('#mirror-feedback').textContent='그림자가 손을 뻗었다가 멈춘다. 유리 위쪽 행부터 읽었는지 살펴보자.';return;}S().shadow=true;seal('audit');eventPanel('유리 너머에서 누군가 걸어 나왔다','검은 형체가 발뒤꿈치에 붙었다. 한 발 움직이자 따라온다.\n거울 속의 내가 쪽지를 내민다. “성문에서는 내가 먼저 갈게. 원본 도안만 좀 찾아줘.”');}

function shadowSize(){return S().lamp==='near'?3:S().lamp==='middle'?2:S().lamp==='far'?1:0;}
function exitPanel(){const size=shadowSize(),right=S().screen===0;panel('성문 · 그림자 대조 센서',`<p>오른쪽 벽의 틀은 사람 모양이다. 바닥에는 등 받침을 놓을 홈 세 개와 방향 레일이 있다.</p><div class="shadow-lab ${right?'':'light-right'} ${S().blind?'':'double-light'}"><div class="light-source">${S().lamp?'◈':'빈 받침'}</div><div class="person">♟</div><div class="sensor ${S().blind&&S().shadow&&size===2&&right?'aligned':''}"><span class="projected" style="transform:scale(${S().shadow&&right&&size?size/2:0})">♟</span><small>센서 틀</small></div></div><div class="device-readout">창빛: ${S().blind?'차단됨':'유입 중'} / 등 위치: ${{near:'가까이',middle:'중간',far:'멀리'}[S().lamp]||'미설치'}<br>${!S().shadow?'바닥에 그림자가 없다.':!size?'등 받침이 비어 있다.':!S().blind?'창빛 때문에 윤곽이 두 겹이다.':!right?'그림자가 왼쪽 벽으로 향한다.':size===1?'그림자가 센서보다 작다.':size===3?'그림자가 센서 밖으로 넘친다.':'그림자의 윤곽이 센서에 맞는다.'}</div>${S().lamp?`<div class="actions">${[['far','멀리'],['middle','중간'],['near','가까이']].map(([k,n])=>`<button class="secondary" onclick="S().lamp='${k}';save();exitPanel()">등을 ${n}${S().lamp===k?' ✓':''}</button>`).join('')}<button class="secondary" onclick="S().screen=1-S().screen;save();exitPanel()">등을 ${right?'오른쪽':'왼쪽'} 레일로</button></div>`:''}<div class="actions"><button class="secondary" onclick="interact('blind')">차광막 기어함</button><button class="secondary" onclick="readDoc('light')">경비 일지 읽기</button><button class="primary" onclick="attemptExit()">문 손잡이 당기기</button></div><p id="exit-feedback" role="status"></p>`,'terminal');}
function attemptExit(){if(!S().shadow||!S().blind||S().lamp!=='middle'||S().screen!==0){$('#exit-feedback').textContent='잠금쇠는 그대로다. 센서와 그림자의 윤곽을 비교해보자.';return;}state.ended=true;save();render();ending();}
ending=function(){panel('본인과 그림자, 모두 퇴실.',`<div class="ending-stamp">18:04 사건 종결</div><p>그림자가 완성된 인영 안으로 들어갔다. 잠금쇠가 풀리고, 이번에는 둘 다 문을 나섰다.</p><p>뒤에서 뼈 대리가 외친다.<br>“반납대에 물건은 두고 가셨어요?”<br>그림자가 대신 손을 흔들었다. 오늘의 대답은 그걸로 충분했다.</p><button class="primary" onclick="closeModal()">퇴근하기</button><button class="secondary" onclick="notebook()">조사 수첩 돌아보기</button>`);};

interact=function(id){switch(id){
 case'org':pipePanel();break;
 case'skeleton':panel('뼈 대리',`<p>“명판이 없어져서 본인 확인이 안 되나 봐요. 미믹이 점심에 금속을 씹던데.”</p><p>“기록실과 감사부는 걸어갈 수 있어요. 시설부만 접혀 버렸죠. 손잡이를 빌려 쓴 사람이 있을 텐데…”</p><button class="secondary" onclick="readDoc('rules')">사고 접수 기록 보기</button>`);break;
 case'rules':discover('rules');panel('사고 접수철',`<div class="document-body">${esc(docs.rules[1])}</div><p>서류에 임시 사원증이 끼워져 있다.</p>${owns('badge')?'<p class="sub">사원증은 챙겼다.</p>':'<button class="primary" onclick="take(\'badge\')">사원증 챙기기</button>'}<button class="secondary" onclick="readDoc('rules')">기록 고정하기</button>`);break;
 case'drawer':panel('개인 비품 서랍',S().drawer?'<p>천과 휴대등을 챙긴 자리다.</p>':'<p>손잡이 옆에 얇은 접점 슬롯이 있다. “인사부 발급 / 본인 비품함”이라고 적혀 있다.</p>','drawer');break;
 case'candle':panel('불씨 양초',`<p>꺼지지 않는 불씨. 손을 가까이 대면 열기가 느껴진다.</p>${owns('candle')||owns('cold')||has('facility')?'<p>양초를 가져간 자리다.</p>':'<button class="primary" onclick="take(\'candle\')">챙기기</button>'}`);break;
 case'window':panel('감사부 창문',`<p>창은 열려 있고 황동 손잡이는 분리되어 창틀 위에 놓여 있다. 축 끝이 사각형이다.</p>${owns('crank')||S().crank?'<p>손잡이를 가져간 자리다.</p>':'<button class="primary" onclick="take(\'crank\')">손잡이 챙기기</button>'}`);break;
 case'ice':panel('만년빙 보관함',`<p>${S().thawed?'손잡이의 성에가 녹아 문이 열린다. 안의 푸른 얼음은 멀쩡하다.':'안쪽에 얼음이 보이지만 손잡이가 서리에 붙었다.'}</p>${S().thawed&&!owns('ice')&&!owns('cold')&&!has('facility')?'<button class="primary" onclick="take(\'ice\')">얼음 꺼내기</button>':''}<button class="secondary" onclick="readDoc('cooling')">옆의 냉각 기록 읽기</button>`,'ice');break;
 case'mimic':panel('미믹 주임',`<p>${has('facility')?'“명판 돌려드렸잖아요. 빈 접시까지 가져가실 건 아니죠?”':'이빨 사이에 금속판이 끼어 있다.\n“꺼내 드릴 수는 있는데, 우선 제대로 된 저녁 좀 주세요.”'}</p><button class="secondary" onclick="readDoc('feeding')">식판의 반려 목록 살펴보기</button>`,has('facility')?null:'mimic');break;
 case'diet':readDoc('feeding');break;
 case'shelf':shelfPanel();break;
 case'shelfNote':readDoc('shelf');break;
 case'workbench':workbench();break;
 case'registration':case'auditRules':readDoc('registration');break;
 case'mirror':mirrorPanel();break;
 case'light':case'tomorrow':readDoc('light');break;
 case'blind':panel('차광막 기어함',`<p>${S().gear?'교체한 톱니가 맞물려 있다. 손잡이가 움직인다.':'톱니 하나가 빠져 줄을 당겨도 헛돈다. 꼬리표: “교체품은 기록실 반납 서랍”.'}</p>${S().gear?`<button class="primary" onclick="S().blind=!S().blind;save();render();interact('blind')">차광막 ${S().blind?'열기':'닫기'}</button><p>${S().blind?'창빛이 차단되었다.':'창빛이 바닥을 비춘다.'}</p>`:''}<button class="secondary" onclick="exitPanel()">센서로 돌아가기</button>`,'blind');break;
 case'terminal':exitPanel();break;
 default:readDoc('rules');
}};
const hints={
 hr:['서류철에 끼운 물건과 서랍의 슬롯을 비교해보세요. 복도 손잡이는 다른 방에 있습니다.','사원증으로 인사부 서랍을 열고, 감사부 창틀에서 황동 손잡이를 가져오세요.','황동 손잡이를 조직도에 사용한 뒤 1→2→5→4→7→8→9를 연결하세요.'],
 archive:['책등의 양끝과 서가 양끝 장식을 비교하세요. 두 책을 누르면 위치가 바뀝니다.','달에서 시작해 깃털, 물결, 태양, 열쇠가 이어져야 합니다.','보안 회의 → 시설 회의 → 급식 회의 → 퇴근 회의 순서로 밀어 넣으세요.'],
 facility:['미믹이 거절한 세 음식에는 각각 다른 문제가 있습니다. 냉각 기록과 비교하세요.','양초로 보관함 손잡이를 녹인 뒤 얼음을 챙기세요. 두 물건은 소지품 조사창에서 조합할 수 있습니다.','양초＋얼음으로 차가운 불꽃을 만들어 미믹에게 사용하세요. 명판은 광택 천과 조합해 닦습니다.'],
 audit:['기록실 작업대에서 대조판과 명판의 잘린 모서리를 맞춰보세요.','투명판과 닦은 명판을 조합한 뒤, 작업대에서 투명판 모서리를 오른쪽 위로 맞추세요. 그 명판을 반사경에 사용합니다.','유리의 위쪽 행부터 읽으면 열쇠 → 왕관 → 태양입니다. 선택 후 이름을 부르세요.'],
 exit:['경비 일지에는 광원 수, 방향, 그림자 크기에 관한 관측이 있습니다.','기록실의 톱니로 차광막을 고쳐 닫고, 휴대등을 센서 앞에 사용하세요.','그림자 복원 후 차광막 닫힘, 등 왼쪽 레일·중간 거리를 맞추고 문을 당기세요.']};
$('#hint').onclick=()=>{const k=state.room;const n=Math.min(S().hints[k]||0,2);S().hints[k]=n+1;save();panel(`이 장소의 힌트 · ${n+1} / 3`,`<p>${hints[k][n]}</p><p class="sub">다음에 누르면 더 구체적인 도움을 줍니다. 수첩에 고정한 자료도 함께 비교하세요.</p>`);};
$('#help').onclick=()=>panel('조사 방법','<p>방 안의 이름표를 누르면 조사합니다.\n소지품을 누르면 앞뒤를 살피거나 다른 물건과 조합할 수 있습니다.\n장치 조사창 아래에서 사용할 물건을 골라 ‘사용’을 누르세요.\n읽은 문서는 조사 수첩에 남습니다. 하나를 고정하면 다른 장치와 나란히 볼 수 있습니다.\n기록실·감사부·성문은 처음부터 탐색할 수 있습니다.</p><div class="clue">F2 업무 모드 · Esc 조사창 닫기<br>시간 제한 없음 · 소리 필수 퍼즐 없음 · 진행 자동 저장</div>');
// A placeholder allows saves in the extension room to load before episode.js.
rooms.mail={en:'문서 수발실',title:'수발실 · 돌아오지 않은 원본',note:'관송기 안에서 봉투가 부딪히는 소리가 난다.',art:()=>'',spots:[]};
save();render();
