// Deterministic interactive diagrams. Prior solved states remain solved.
function V(){if(!E().visual)E().visual={switches:E().power?[1,0,1,1]:[0,0,0,0],path:E().parcel?['s','b','d','f','t']:['s'],tested:false};return E().visual;}
const relayPairs=[[0,2],[1,3],[0,1],[2,3]];
const signalSymbols=['●','▲','■','✦'];
const signalColors=['#53c8cf','#edaf5e','#d588c6','#96bf6e'];
const desiredSignals=[1,2,3,0];
function relayStages(){let values=[0,1,2,3],stages=[values.slice()];relayPairs.forEach(([a,b],i)=>{if(V().switches[i])[values[a],values[b]]=[values[b],values[a]];stages.push(values.slice());});return stages;}
function relayBoard(){const stages=relayStages();let paths='';for(let k=0;k<4;k++){const [a,b]=relayPairs[k];for(let row=0;row<4;row++){const dest=V().switches[k]?(row===a?b:row===b?a:row):row;const x=85+k*110,y=65+row*62,ny=65+dest*62;const sig=stages[k][row];paths+=`<path d="M${x} ${y} C${x+42} ${y} ${x+68} ${ny} ${x+110} ${ny}" fill="none" stroke="#142433" stroke-width="11"/><path d="M${x} ${y} C${x+42} ${y} ${x+68} ${ny} ${x+110} ${ny}" fill="none" stroke="${V().tested?signalColors[sig]:'#6c8390'}" stroke-width="4"/>`;}}
 return `<svg class="relay-board" viewBox="0 0 630 320" role="img" aria-label="네 개의 교차 스위치 회로. 왼쪽 신호가 스위치를 거쳐 오른쪽 단자로 전달됩니다."><rect width="630" height="320" rx="8" fill="#1c2d3c"/>${paths}${[0,1,2,3].map(r=>`<text x="32" y="${72+r*62}" fill="${signalColors[r]}" font-size="25">${signalSymbols[r]}</text><path d="M60 ${65+r*62}H85 M525 ${65+r*62}H553" stroke="#8094a1" stroke-width="4"/><circle cx="560" cy="${65+r*62}" r="15" fill="${V().tested?(stages[4][r]===desiredSignals[r]?'#71d9a7':'#e27475'):'#3d4f5c'}"/><text x="592" y="${73+r*62}" text-anchor="middle" fill="#f5f3ed" font-size="25">${signalSymbols[desiredSignals[r]]}</text>`).join('')}${[0,1,2,3].map(i=>`<text x="${140+i*110}" y="27" text-anchor="middle" fill="#e9ecef" font-size="14">${['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][i]}</text>`).join('')}<text x="22" y="300" fill="#cedce4" font-size="12">입력 신호</text><text x="510" y="300" fill="#cedce4" font-size="12">출력 각인</text></svg>`;
}
wiringPanel=function(){panel('관송기 배전함',`<p>오른쪽 단자의 각인은 원래 연결된 신호다. 네 개의 스위치가 각각 두 선의 길을 교환한다. 왼쪽 신호를 같은 각인의 단자로 보내야 한다.</p>${relayBoard()}<div class="relay-controls">${[0,1,2,3].map(i=>`<button class="secondary ${V().switches[i]?'engaged':''}" onclick="flipRelay(${i})"><b>${['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][i]}</b><span>${V().switches[i]?'╳ 교차':'Ⅱ 직결'}</span></button>`).join('')}</div><div class="relay-results">${V().tested?relayStages()[4].map((s,r)=>`<span>${signalSymbols[s]} → ${signalSymbols[desiredSignals[r]]} ${s===desiredSignals[r]?'✓':'불일치'}</span>`).join(''):'전원을 넣으면 전류가 흐르는 선과 각 단자의 반응이 표시됩니다.'}</div><div class="actions"><button class="secondary" onclick="readDoc('wires')">뚜껑의 주의사항</button><button class="primary" onclick="checkWires()">전원 넣기</button></div><p id="wire-feedback" role="status">${E().power?'관송기 전원은 복구되어 있습니다.':''}</p>`);};
function flipRelay(i){V().switches[i]=1-V().switches[i];V().tested=false;save();wiringPanel();}
checkWires=function(){V().tested=true;const solved=relayStages()[4].every((s,i)=>s===desiredSignals[i]);if(solved)E().power=true;save();render();wiringPanel();$('#wire-feedback').textContent=solved?'네 단자에 올바른 신호가 들어왔다. 관송기가 깨어난다.':'붉게 켜진 단자는 다른 신호를 받았다. 그 선을 거슬러 올라가 스위치를 살펴보자.';};
docs.wires=['배전함 뚜껑의 주의사항','교차 스위치는 두 선의 목적지를 서로 바꾼다. 그 외의 선은 통과한다.\n선이 교차하는 지점에는 접속점이 없다.\n오른쪽 단자 옆 각인은 필요한 입력 신호다.\n전원 시험: 일치하면 녹색, 불일치하면 적색. 기호와 글자로도 결과를 확인할 수 있다.'];

const tubeNodes={
 s:{x:42,y:175,label:'발송함',edges:['a','b']},
 a:{x:175,y:65,label:'상층관',hazard:'water',mark:'물방울',edges:['c','d']},
 b:{x:175,y:290,label:'하층관',edges:['d','e']},
 c:{x:330,y:55,label:'보일러 옆',hazard:'heat',mark:'열기',edges:['f']},
 d:{x:330,y:175,label:'중앙 우회관',edges:['f','g']},
 e:{x:330,y:305,label:'세척실 위',hazard:'water',mark:'수증기',edges:['g']},
 f:{x:495,y:100,label:'암실 옆',edges:['t']},
 g:{x:495,y:260,label:'채광창 옆',hazard:'light',mark:'햇빛',edges:['t']},
 t:{x:650,y:175,label:'회수함',edges:[]}
};
function tubeMap(interactive){const path=V().path;let lines='';for(const [id,n] of Object.entries(tubeNodes))for(const next of n.edges){const m=tubeNodes[next];const traced=path.some((p,i)=>p===id&&path[i+1]===next);lines+=`<path d="M${n.x} ${n.y} L${m.x} ${m.y}" stroke="${traced?'#57ddd1':'#748594'}" stroke-width="${traced?7:3}" fill="none"/>`;}
 const last=path.at(-1);return `<div class="tube-scroll"><div class="tube-map"><svg viewBox="0 0 700 360" aria-hidden="true">${lines}</svg>${Object.entries(tubeNodes).map(([id,n])=>`<button class="tube-node ${path.includes(id)?'selected':''} ${interactive&&tubeNodes[last].edges.includes(id)?'available':''}" style="left:${n.x/7}%;top:${n.y/3.6}%" onclick="${interactive?`chooseTube('${id}')`:`tubeEvidence('${id}')`}" aria-label="${n.label}${n.mark?' · '+n.mark:''}"><b>${id==='s'?'▣':id==='t'?'▤':n.hazard==='water'?'♒':n.hazard==='heat'?'♨':n.hazard==='light'?'☀':'○'}</b><span>${n.label}</span>${n.mark?`<small>${n.mark}</small>`:''}</button>`).join('')}</div></div>`;}
docs.ink=['빛에 드러난 운송장','내용물: 그림자 감광 필름 원본.\n시험편 사고: 물에 젖은 필름은 인영이 번졌다. 뜨거워진 필름은 수축했다. 빛에 노출된 필름은 하얗게 날아갔다.\n방습·차광 케이스 파손. 이번 운송에는 보호 기능이 없다.\n회수함까지 원형을 보존할 수 있는 관을 선택할 것.'];
docs.transit=['관송관 약도','관은 왼쪽 발송함에서 오른쪽 회수함으로 이어진다.\n♒: 물방울 또는 수증기 흔적 / ♨: 고열 / ☀: 채광\n동그라미는 흔적이 발견되지 않은 중계함.\n운송물마다 견딜 수 있는 환경이 다르다. 기록실의 빈 운송장에서 내용물을 확인할 것.'];
rooms.mail.note='벽의 관송관 약도에는 물방울과 그을음 자국이 남아 있다. 봉투가 무엇을 담고 있는지 알아야 안전한 관을 고를 수 있다.';
transitPanel=function(){panel('문서 관송기',`<p>연결된 중계함을 눌러 봉투가 지나갈 길을 정하세요. 선택한 지점을 다시 누르면 그 뒤의 경로를 지웁니다.</p>${tubeMap(true)}<div class="device-readout">선택 경로: ${V().path.map(id=>tubeNodes[id].label).join(' → ')}</div><div class="actions"><button class="secondary" onclick="V().path=['s'];save();transitPanel()">경로 지우기</button><button class="secondary" onclick="readDoc('transit')">벽의 약도 조사</button><button class="primary" ${E().power?'':'disabled'} onclick="sendParcel()">봉투 운송</button></div><p id="transit-feedback" role="status">${E().parcel?'원본 봉투를 이미 회수했습니다. 경로를 다시 살펴볼 수 있습니다.':E().power?'전원 정상 · 회수함까지 경로를 지정하세요.':'전원이 없습니다. 배전함부터 복구하세요.'}</p>`);};
function chooseTube(id){const path=V().path;if(path.includes(id)){V().path=path.slice(0,path.indexOf(id)+1);}else if(tubeNodes[path.at(-1)].edges.includes(id)){path.push(id);}else{toast('현재 경로 끝과 관으로 연결된 중계함을 선택하세요.');return;}save();transitPanel();}
sendParcel=function(){if(!E().power)return;const msg=$('#transit-feedback');if(V().path.at(-1)!=='t'){msg.textContent='경로가 회수함에 닿지 않았습니다.';return;}const broken=V().path.find(id=>tubeNodes[id].hazard);if(broken){const n=tubeNodes[broken];msg.textContent=`${n.label}의 감지기가 운송을 중단했다. ${ {water:'수분이 케이스 틈으로 들어오려 한다.',heat:'필름 포장이 열에 뒤틀린다.',light:'감광 표시가 빛에 반응한다.'}[n.hazard]} 원본은 발송함으로 회수됐다.`;return;}if(E().parcel){msg.textContent='안전한 경로입니다. 원본 봉투는 소지품에 있습니다.';return;}E().parcel=true;grant('packet');eventPanel('손상 없이 도착한 원본','봉투가 선택한 관을 따라 회수함으로 미끄러져 나왔다. 필름에는 얼룩도 그을음도 없다.\n원본 도안과 세 장의 필름을 성문 판독기에 사용할 수 있다.');};
const textReadDoc=readDoc;
readDoc=function(id){if(id!=='transit'){textReadDoc(id);return;}discover(id);if(!documentOrigin)documentOrigin=currentView;currentDocument=id;corePanel('관송관 약도',`<button class="secondary" onclick="returnToProblem()">← 이전 화면으로</button><p>정비사가 관 주변에서 발견한 흔적을 표시했다. 중계함을 눌러 자세히 조사할 수 있다.</p>${tubeMap(false)}<p id="tube-evidence" role="status">이 지도에는 배송 순서가 없다. 운송장 속 내용물과 흔적을 비교하자.</p><div class="actions"><button class="secondary" onclick="pinDoc('transit')">범례 고정 / 해제</button><button class="primary" onclick="returnToProblem()">조사를 마치고 돌아가기</button></div>`);};
function tubeEvidence(id){const n=tubeNodes[id];$('#tube-evidence').textContent=n.label+': '+({a:'연결관 아래에 물방울이 맺혀 있다.',b:'관은 서늘하고 마른 상태다.',c:'외벽의 페인트가 열에 벗겨져 있다.',d:'우회관 안쪽에 습기나 열 흔적이 없다.',e:'세척실에서 올라온 증기가 관 안에 맺힌다.',f:'차광 덮개가 관 전체를 가리고 있다.',g:'유리관에 햇빛이 그대로 들어온다.',s:'반송된 봉투를 출발시키는 곳.',t:'성문으로 가져갈 원본을 받는 곳.'}[id]);}
problemHints.wiring=['스위치를 누르면 두 선이 서로 교차합니다. 선의 변화부터 살펴보세요.','출력은 위부터 ▲·■·✦·●를 요구합니다. 전원 시험 후 잘못 도착한 신호를 거슬러 올라가 보세요.','Ⅰ 교차, Ⅱ 직결, Ⅲ 교차, Ⅳ 교차로 맞추고 전원을 넣으세요.'];
problemHints.transit=['관송관 약도는 길과 흔적을 보여줍니다. 봉투 내용물의 약점은 다른 자료에 있습니다.','기록실의 빈 운송장에 휴대등을 사용하세요. 물·열·빛을 피할 수 있는 관을 찾아야 합니다.','발송함 → 하층관 → 중앙 우회관 → 암실 옆 → 회수함을 선택하고 운송하세요.'];
problemHints.ink=['운송장의 글씨는 지워진 것이 아니라 감춰져 있습니다.','휴대등으로 종이를 뒤에서 비추세요.','빈 운송장에 휴대등을 사용하면 필름이 물·열·빛에 손상된다는 기록이 나타납니다.'];
V();save();
